baseURL = 'https://sardanisca-website.netlify.app/'
languageCode = 'pt-PT'
title = 'Centro Cultural Sardanisca'
defaultContentLanguage = "pt"
theme = ["hugo-cloak-email", "sardanisca"]
copyright = "Sardanisca"
pagination.PageSize = 15
refLinksErrorLevel = "WARNING"

[params]
description = "Site do Centro Cultural Sardanisca"
keywords = "Arte, Música, Alentejo"
mode = "toggle"
date_format = "2.Jan2006"

[permalinks]
posts = "/:year/:slug/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/sardanisca.centrocultural/"

[[menu.main]]
  name = "Sobre"
  url = "/sobre/"
  weight = 1

[[menu.main]]
  name = "Eventos"
  url = "/eventos/"
  weight = 2

[[menu.main]]
  name = "Residências"
  url = "/residencias/"
  weight = 3
