baseURL = 'https://sardanisca.org/'
languageCode = 'pt-PT'
title = 'Centro Cultural Sardanisca'
defaultContentLanguage = "pt"
theme = 'sardanisca'
copyright = "Nuno Godinho"
pagination.PageSize = 15
refLinksErrorLevel = "WARNING"

[params]
description = "Site do Centro Cultural Sardanisca"
keywords = "Arte, Música, Alentejo"
mode = "toggle"

[permalinks]
posts = "/:year/:slug/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/sardanisca.centrocultural/"

[[menu.main]]
  name = "Sobre"
  url = "/sobre/"
  weight = 1

[[menu.main]]
  name = "Residências"
  url = "/residencias/"
  weight = 2

[[menu.main]]
  name = "Programação"
  url = "/programacao/"
  weight = 3

[[menu.main]]
  name = "Formação"
  url = "/formacao/"
  weight = 4
