baseURL = 'https://sardanisca.org'
title = 'Centro Cultural Sardanisca'
theme = ["hugo-cloak-email", "sardanisca", "archie"]
copyright = "Sardanisca"
pagination.PageSize = 15
refLinksErrorLevel = "WARNING"
defaultContentLanguage = "pt"

[languages]
  [languages.pt]
    languageCode = 'pt-PT'
    languageName = 'Português'
    weight = 1
    title = 'Centro Cultural Sardanisca'
    [languages.pt.params]
      description = "Site do Centro Cultural Sardanisca"
      keywords = "Arte, Música, Alentejo"
    [[languages.pt.menu.main]]
      name = "Sobre"
      url = "/sobre/"
      weight = 1
    [[languages.pt.menu.main]]
      name = "Residências"
      url = "/residencias/"
      weight = 2
    [[languages.pt.menu.main]]
      name = "Eventos"
      url = "/eventos/"
      weight = 3

  [languages.en]
    languageCode = 'en-GB'
    languageName = 'English'
    weight = 2
    title = 'Sardanisca Cultural Centre'
    [languages.en.params]
      description = "Sardanisca Cultural Centre website"
      keywords = "Art, Music, Alentejo"
    [[languages.en.menu.main]]
      name = "About"
      url = "/sobre/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Residencies"
      url = "/residencias/"
      weight = 2
    [[languages.en.menu.main]]
      name = "Events"
      url = "/eventos/"
      weight = 3

[params]
date_format = "2.Jan2006"
mathjax = false
katex = false
customCSS = ["css/main-overrides.css", "css/extra.css", "css/fancybox-custom.css", "css/gallery.css"]

[permalinks]
posts = "/:year/:slug/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/sardanisca.centrocultural/"

[[params.social]]
name = "E-mail"
icon = "mail"
url = "mailto:info@sardanisca.org"