baseURL = 'https://sardanisca.org'
languageCode = 'pt-PT'
title = 'Centro Cultural Sardanisca'
defaultContentLanguage = "pt"
theme = ["hugo-cloak-email", "sardanisca"]
copyright = "Sardanisca"
pagination.PageSize = 15
refLinksErrorLevel = "WARNING"
relativeURLs = true

[params]
description = "Site do Centro Cultural Sardanisca"
keywords = "Arte, Música, Alentejo"
date_format = "2.Jan2006"
mathjax = false
katex = false
customCSS = ["css/fancybox-custom.css", "css/gallery.css"]

[permalinks]
posts = "/:year/:slug/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/sardanisca.centrocultural/"

[[params.social]]
name = "E-mail"
icon = "mail"
url = "mailto:info@sardanisca.org"

[[menu.main]]
  name = "Sobre"
  url = "/sobre/"
  weight = 1

[[menu.main]]
  name = "Eventos"
  url = "/eventos/"
  weight = 2

[[menu.main]]
  name = "Residências"
  url = "/residencias/"
  weight = 3
